# Default values for myChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3
namespace:
  name: demo

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: alpine

configmap:
  data: "version:alpine"

service:
  port: 8111
  type: ClusterIP

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}

resources:
  requests:
    cpu: 50m
    memory: 256Mi

service:
  type: ClusterIP
  port: 80
